name: workflow-03

on:
  workflow-dispatch

jobs:
  my-job:
    runs-on: ubuntu-latest

    steps:
      - name: This is first step to trigger the workflow manually
        run: echo "Hello running workflow manually"
