name: This is my 3rd workflow

on:
  workflow_dispatch:

jobs:
  code:
    runs-on: ubuntu-latest

    steps:
      - name: Clone the code
        run: echo "Cloning the code"
  
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Build the code
        run: echo "Building using Docker"

  Test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Running test cases
        run: echo "Testing the app"

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: deploying the code
        run: echo "Deploying the code"